// default package
// Generated 09-dic-2019 19:22:21 by Hibernate Tools 5.2.12.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Modulo generated by hbm2java
 * Este modulo tenia un Set de profesores porque hibernate lo ha hecho en dos direcciones, pero lo he quitado.
 */
@Entity
@Table(name = "Modulo", catalog = "profesor_ejercicio3")
public class Modulo implements java.io.Serializable {

	private Integer id;
	private String nombre;

	public Modulo() {
	}

	public Modulo(String nombres) {
		this.nombre = nombre;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "Id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "nombre")
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	
}
